# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78af53e868f851704139d02da3be81b57f0f4d2904fd43752a9574d90ee7c9b2eb360c560d00358af84dbc1eb5e630f18dee8795b31003811de570e00a4f3af8

test:
  secret_key_base: 8ca152a1e49bff14367bff73f5e31dca8ba1448d6c0cc78ea7525299ece91bbbd164fa7e3ffdc2ccaa083503737de36770a2d50bea6dd6dae721f18e257ecb0f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
